### ISSUE TITLE
Radius does not change

### ISSUE THREAD

**Issue by S-Berhane** [mourner/simpleheat#12]
I've been trying to change the radius using heat.radius(r,blur) but it never changes.
I suspect that something is reverting the radius to the default. I added a console.log to the radius method and called it once in my script. For some reason though radius change function ran twice. The first run my input is the same but the second one, the variable blur becomes undefined, which gives it a value of 15.

**Comment by mourner** [comment]
Can you set up a minimal JSFiddle test case reproducing the issue?

**Comment by S-Berhane** [comment]
https://jsfiddle.net/mta044yy/1/

This is somewhat close to my actual implementation, but the problem is reproduced. I may be implementing this the wrong way though.

**Comment by mourner** [comment]
Yeah, turned out to be a misuse of the library. You created a new simpleheat object every time instead of calling draw on the original one. Working JSFiddle: https://jsfiddle.net/mta044yy/2/
