### ISSUE TITLE
question 

### ISSUE THREAD

**Issue by publicocean0** [mourner/simpleheat#19]
hi,i m evauluating to use in future your tiny library. It seams very fast :) i have a doubt .... 
how can put a overlay image under the heatmap?

**Comment by mourner** [comment]
Canvas is semitransparent. Just position an image underneath with basic CSS.

**Comment by publicocean0** [comment]
ah ok it seams simple :) a question.. if you have  time for comment ... i overvewed your code for understanding how you calculate the color that is changing based on the times you pass over it. 
Stranally i cant identity the exact point .... probably i dont know exactly how works color gradients. 

`for (var i = 0, len = this._data.length, p; i < len; i++) {
            p = this._data[i];
            ctx.globalAlpha = Math.max(p[2] / this._max, minOpacity === undefined ? 0.05 : minOpacity);
            ctx.drawImage(this._circle, p[0] - this._r, p[1] - this._r);
        }`  

      ctx.globalAlpha opacity is proprtional to value intensity... not the frequency of a point x,y.
     drawImage draws a circle.....

**Comment by publicocean0** [comment]
_colorize: function (pixels, gradient) {
        for (var i = 0, len = pixels.length, j; i < len; i += 4) {
            j = pixels[i + 3] * 4; // get gradient color from opacity value

            if (j) {
                pixels[i] = gradient[j];
                pixels[i + 1] = gradient[j + 1];
                pixels[i + 2] = gradient[j + 2];
            }
        }
    },
