### ISSUE TITLE
Is it possible to select adjacent same color points

### ISSUE THREAD

**Issue by tanmuhittin** [mourner/simpleheat#22]
1. Draw the map using data
2. Color values are changing between 0 and 1
3. Pick a point on the map where there is not a sample
4. Select the samples in the area where the color value is +-0.05 different than the selected point and adjacent
Can we select them ?

**Comment by mourner** [comment]
I didn't really understand what you want to do, but it's probably not the responsibility of the library. You can get pixel data from the canvas though, and do your own logic for this.

**Comment by tanmuhittin** [comment]
thank you for the quick answer I will look for canvas solutions 👍
