### ISSUE TITLE
simpleheat.js:87 Uncaught DOMException: Failed to execute 'addColorStop' on 'CanvasGradient': The provided value (5) is outside the range (0.0, 1.0).

### ISSUE THREAD

**Issue by NithyaSangeeth** [mourner/simpleheat#40]
A DOM Exception is raised while rendering the page . Tried to go through the simpleheat.js file, but don't know where to change the range.

Need the defaultGradient to be 
defaultGradient: {
        5.0: 'blue',
        10.0: 'cyan',
        15.0: 'lime',
        20.0: 'yellow',
        25.0: 'red'
    },

Any help is appreciated . Thanks in advance.

**Comment by mourner** [comment]
The stop values can only be in the 0..1 range, as the error says.
