### ISSUE TITLE
bower: no master branch.

### ISSUE THREAD

**Issue by Syam** [mourner/simpleheat#5]
Can't use this repo via bower, because of missing master branch.

**Comment by mourner** [comment]
I think that's Bower's problem. Using `gh-pages` as the default branch on GitHub instead of `master` is a pretty common practice.

**Comment by Syam** [comment]
The issue here may not be Bower's feature-set, but with the practice of software development with Bower.

gh-pages branch is for project page purpose :

> The gh-pages branch is used to build and publish Project Pages sites.
> https://help.github.com/articles/user-organization-and-project-pages/

Quote from github's blog:

> The best system we've found so far to provide this flexibility is to have people deploy branches. Changes never get merged to master until they have been verified to work in production from a branch. This means that master is always stable; a safe point that we can roll back to if there's a problem.
> https://github.com/blog/1241-deploying-at-github

Another quote from a bower user:

> Bower shouldn't magically consume everything which remotely resembles a package. It should be to educate authors to improve their repos and publish bower consumable packages.
> 
> Historically that's how package managers have worked… and there's a reason for that.
> 
> Package managers need to rely on package maintainers to tell us when a package is reliable – not the other way around.

So, please, can you indicate which version of your project is stable, by using appropiates master-branch and tags ?
