### ISSUE TITLE
minOpacity || 0.05

### ISSUE THREAD

**Issue by fatore** [mourner/simpleheat#6]
I had a problem with this line:

ctx.globalAlpha = Math.max(p[2] / this._max, minOpacity || 0.05);

In my app, I had clusters of elements with zero values, but the heatmap "insisted" that was something there. So I checked the source code and notice that the "|| 0.05" can lead to artifacts in the visualization, so I simply removed that and everything looks real now.

I don't know what you had in mind when you set that threshold, but I think it would be better to rely only on the minOpacity parameter.

**Comment by mourner** [comment]
Thanks, fixed — you can now use `0` as `minOpacity` when calling `draw`.
